version: "3.5"

services:
  test:
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    volumes:
      - type: bind
        source: C:\Users\stefan\.ssh
        target: C:\ssh
    command: cmd /C dir C:\ssh

networks:
  default:
    external:
      name: nat
